# Title of the document
title: "GDELT Events EDA - latest datafile"

# Metadata
dataset:
  description: "GDELT - Events table records from the latest datafile, with a number of dropped columns. (See project documentation for details. All variable descriptions are by reference from http://data.gdeltproject.org/documentation/GDELT-Event_Codebook-V2.0.pdf)"
  creator: "Leetaru, K. & Schrodt, P. A."
  author: "Richard Allan Smith Jr."
  copyright_holder: "GDELT Project"
  copyright_year: "2013-2021"
  url: "https://www.gdeltproject.org/data"

variables:
    descriptions:
        'Actor1Code' : "(string) The complete raw CAMEO code for Actor1 (includes geographic, class, ethnic, religious, and type classes). May be blank if the system was unable to identify an Actor1"
        'Actor1Name' : "(string) The actual name of the Actor1. In the case of a political leader or organization, this will be the leader's formal name (GEORGE W BUSH, UNITED NATIONS), for a geographic match it will be either the country or capital/major city name (UNITED STATESPARIS), and for ethnic, religious, and type matches it will reflect the root match class (KURD,CATHOLIC, POLICE OFFICER, etc). May be blank if the system was unable to identify an Actor1."
        'Actor1CountryCode' : "(string) The 3-character CAMEO code for the country affiliation of Actor1. May be blank if the system was unable to identify an Actor1 or determine its country affiliation(such as 'UNIDENTIFIED GUNMEN')."
        'Actor1Type1Code' : "(string) The 3-character CAMEO code of the CAMEO 'type' or 'role' of Actor1, if specified. This can be a specific role such as Police Forces, Government, Military, Political Opposition, Rebels, etc, a broad role class such as Education, Elites, Media, Refugees, or organizational classes like Non-Governmental Movement. Special codes such as Moderate and Radical may refer to the operational strategy of a group."
        'Actor1Type2Code' : "(string) If multiple type/role codes are specified for Actor1, this returns the second code."
        'Actor1Type3Code' : "(string) If multiple type/role codes are specified for Actor1, this returns the third code."
        'Actor2Code' : "See descriptions for equivalent Actor1 fields."
        'Actor2Name' : "See descriptions for equivalent Actor1 fields."
        'Actor2CountryCode' : "See descriptions for equivalent Actor1 fields."
        'Actor2Type1Code' : "See descriptions for equivalent Actor1 fields."
        'Actor2Type2Code' : "See descriptions for equivalent Actor1 fields."
        'Actor2Type3Code' : "See descriptions for equivalent Actor1 fields."
        'IsRootEvent' : "(integer) The system codes every event found in an entire document, using an array of techniques to deference and link information together. A number of previous projects such as the ICEWS initiative have found that events occurring in the lead paragraph of a document tend to be the most 'important.' This flag can therefore be used as a proxy for the rough importance of an event to create subsets of the event stream. NOTE: this field refers only to the first news report to mention an event and is not updated if the event is found in a different context in other news reports. It is included for legacy purposes--for more precise information on the positioning of an event, see the Mentions table."
        'EventCode' : "(string) This is the raw CAMEO action code describing the action that Actor1 performed upon Actor2. NOTE: it is strongly recommended that this field be stored as a string instead of an integer, since the CAMEO taxonomy can include zero-leaded event codes that can make distinguishing between certain event types more difficult when stored as an integer."
        'AvgTone' : "(numeric) This is the average 'tone' of all documents containing one or more mentions of this event during the 15 minute update in which it was first seen. The score ranges from -100 (extremely negative) to +100 (extremely positive). Common values range between -10 and +10, with 0 indicating neutral. This can be used as a method of filtering the 'context' of events as a subtle measure of the importance of an event and as a proxy for the 'impact' of that event. For example, a riot event with a slightly negative average tone is likely to have been a minor occurrence, whereas if it had an extremely negative average tone, it suggests a far more serious occurrence. A riot with a positive score likely suggests a very minor occurrence described in the context of a more positive narrative (such as a report of an attack occurring in a discussion of improving conditions on the ground in a country and how the number of attacks per day has been greatly reduced). NOTE: this field refers only to the first news report to mention an event and is not updated if the event is found in a different context in other news reports. It is included for legacy purposes--for more precise information on the positioning of an event, see the Mentions table. NOTE: this provides only a basic tonal assessment of an article and it is recommended that users interested in emotional measures use the Mentions and Global Knowledge Graph tables to merge the complete set of 2,300 emotions and themes from the GKG GCAM system into their analysis of event records."
        'QuadClass' : "(integer) The entire CAMEO event taxonomy is ultimately organized under four primary classifications: Verbal Cooperation, Material Co operation, Verbal Conflict, and Material Conflict. This field specifies this primary classification for the event type, allowing analysis at the highest level of aggregation. The numeric codes in this field map to the Quad Classes as follows: 1=Verbal Cooperation, 2=Material Cooperation, 3=Verbal Conflict, 4=Material Conflict."
        'Actor1Geo_Type' : "(string) This field specifies the geographic resolution of the match type and holds one of the following values: 1=COUNTRY (match was at the country level), 2=USSTATE (match was to a US state), 3=USCITY (match was to a US city or landmark), 4=WORLDCITY (match was to a city or landmark outside the US), 5=WORLDSTATE (match was to an Administrative Division 1 outside the US--roughly equivalent to a US state). This can be used to filter events by geographic specificity, for example, extracting only those events with a landmark-level geographic resolution for mapping. Note that matches with codes 1 (COUNTRY), 2 (USSTATE), and 5 (WORLDSTATE) will still provide a latitude/longitude pair, which will be the centroid of that country or state, but the FeatureID field below will be blank."
        'Actor1Geo_FullName' : "(string) This is the full human-readable name of the matched location. In the case of a country it is simply the country name. For US and World states it is in the format of 'State, Country Name', while for all other matches it is in the format of 'City/Landmark, State, Country'. This can be used to label locations when placing events on a map. NOTE: this  field reflects the precise name used to refer to the location in the text itself, meaning it may contain multiple spellings of the same location--use the FeatureID column to determine whether two location names refer to the same place."
        'Actor1Geo_Lat' : "(floating point) This is the centroid latitude of the landmark for mapping."
        'Actor1Geo_Long' : "(floating point) This is the centroid longitude of the landmark for mapping."
        'Actor2Geo_Type' : "See descriptions for equivalent Actor1 fields."
        'Actor2Geo_FullName' : "See descriptions for equivalent Actor1 fields."
        'Actor2Geo_Lat' : "See descriptions for equivalent Actor1 fields."
        'Actor2Geo_Long' : "See descriptions for equivalent Actor1 fields."
        'ActionGeo_Type' : "See descriptions for equivalent Actor1 fields."
        'ActionGeo_FullName' : "See descriptions for equivalent Actor1 fields."
        'ActionGeo_Lat' : "See descriptions for equivalent Actor1 fields."
        'ActionGeo_Long' : "See descriptions for equivalent Actor1 fields."
        'DATEADDED' : "(integer) This field stores the date the event was added to the master database in YYYYMMDDHHMMSS format (parsed to Pandas datetime) in the UTC timezone. For those needing to access events at 15 minute resolution, this is the field that should be used in queries. Converted in cleaning to ISO date format."
        'SOURCEURL' : "(string) This field records the URL or citation of the first news report it found this event in. In most cases this is the first report it saw the article in, but due to the timing and flow of news reports through the processing pipeline, this may not always be the very first report, but is at least in the first few reports."

# infer dtypes
infer_dtypes: false

# Show the description at each variable (in addition to the overview tab)
show_variable_description: true

# Number of workers (0=multiprocessing.cpu_count())
pool_size: 0

# Show the progress bar
progress_bar: true

# Per variable type description settings
vars:
    num:
        quantiles:
              - 0.05
              - 0.25
              - 0.5
              - 0.75
              - 0.95
        skewness_threshold: 20
        low_categorical_threshold: 0
        # Set to zero to disable
        chi_squared_threshold: 0.999
    cat:
        length: false
        characters: false
        words: false
        cardinality_threshold: 3000
        n_obs: 30
        # Set to zero to disable
        chi_squared_threshold: 0.999
        coerce_str_to_date: true
        redact: false
        histogram_largest: 50
    bool:
        n_obs: 3
        # string to boolean mapping dict
        mappings:
            t: true
            f: false
            yes: true
            no: false
            y: true
            n: false
            true: true
            false: false
    file:
        active: false
    image:
        active: false
        exif: true
        hash: true
    path:
        active: false
    url:
        active: true

# Sort the variables. Possible values: "ascending", "descending" or null (leaves original sorting)
sort: null

# which diagrams to show
missing_diagrams:
    bar: true
    matrix: false
    heatmap: false
    dendrogram: false

correlations:
    pearson:
      calculate: true
      warn_high_correlations: true
      threshold: 0.9
    spearman:
      calculate: false
      warn_high_correlations: false
      threshold: 0.9
    kendall:
      calculate: false
      warn_high_correlations: false
      threshold: 0.9
    phi_k:
      calculate: false
      warn_high_correlations: false
      threshold: 0.9
    cramers:
      calculate: false
      warn_high_correlations: true
      threshold: 0.9


# Bivariate / Pairwise relations
interactions:
  targets: ['AvgTone', 'DATEADDED']
  continuous: true

# For categorical
categorical_maximum_correlation_distinct: 100

report:
  precision: 10

# Plot-specific settings
plot:
    # Image format (svg or png)
    image_format: "svg"
    dpi: 500

    scatter_threshold: 1000

    correlation:
        cmap: 'RdBu'
        bad: '#000000'

    missing:
        cmap: 'RdBu'
        # Force labels when there are > 50 variables
        # https://github.com/ResidentMario/missingno/issues/93#issuecomment-513322615
        force_labels: true

    pie:
        # display a pie chart if the number of distinct values is smaller or equal (set to 0 to disable)
        max_unique: 10

    histogram:
        x_axis_labels: true

        # Number of bins (set to 0 to automatically detect the bin size)
        bins: 40

        # Maximum number of bins (when bins=0)
        max_bins: 250

# The number of observations to show
n_obs_unique: 20
n_extreme_obs: 10
n_freq_table_max: 30

# Use `deep` flag for memory_usage
memory_deep: false

# Configuration related to the duplicates
duplicates:
    head: 10
    key: "# duplicates"

# Configuration related to the samples area
samples:
    head: 10
    tail: 10
    random: 0

# Configuration related to the rejection of variables
reject_variables: true

# When in a Jupyter notebook
notebook:
    iframe:
        height: '800px'
        width: '100%'
        # or 'src'
        attribute: 'srcdoc'

html:
    # Minify the html
    minify_html: true

    # Offline support
    use_local_assets: true

    # If true, single file, else directory with assets
    inline: true

    # Show navbar
    navbar_show: true

    # Assets prefix if inline = true
    assets_prefix: null

    # Styling options for the HTML report
    style:
      theme: null
      logo: ""
      primary_color: "#337ab7"

    full_width: false